### ISSUE TITLE
Sitemap Not Generating For Routers

### ISSUE THREAD

**Issue by loganknecht** [hex7c0/express-sitemap#3]
I'm not sure if I'm doing something wrong or if this is not supported functionality.

I have an express app that uses a router I created:
```javascript
// Express
var app = express();
```

This router is managed as a module and gets loaded like so:
```javascript
// Routes
var defaultRouter = require('./routers/default-router');
```

So then I set express to use that router:
```javascript
app.use('/', defaultRouter);
```

And then I try to create the site map via express-sitemap:
```javascript
var sitemap = require('express-sitemap');
sitemap = sitemap();
sitemap.generate4(app);
```

Except all it outputs is this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" />
```

Am I misinterpreting the functionality or use case for this module? It appears like I'm following the example I see in the npmjs registry, and github. Can you please elaborate on what I may be doing wrong?

**Comment by hex7c0** [comment]
for nested router `app.use('/', express.Router);` this module can't find appropriate route
you should pass `defaultRouter` or create statically
let me know

**Comment by loganknecht** [comment]
I apologize for my confusion, but I don't really understand what you're trying to communicate?

If you meant passing the defaultRouter to the sitemap object then that doesn't work and gives me this as an error.

```javascript
sitemap.generate4(defaultRouter);
```

```bash
C:\Users\Logan\Repositories\public-site-2.0\node_modules\express-sitemap\index.min.js:46
    for (var routing = app._router.stack, i = 0, ii = routing.length; ii > i;
                                  ^
TypeError: Cannot read property 'stack' of undefined
    at Sitemap.generate4 (C:\Users\Logan\Repositories\public-site-2.0\node_modules\express-sitemap\index.min.js:46:35)
    at Object.<anonymous> (C:\Users\Logan\Repositories\public-site-2.0\server.js:115:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Logan\Repositories\public-site-2.0\bin\www:3:11)
    at Module._compile (module.js:456:26)
```
What am I misunderstanding?

**Comment by hex7c0** [comment]
sorry for my short explanation

did you have a Router like this?
```js
var map = require('..');
var express = require('express');
var father = express();
var child = express();


child.get('/',function(req,res) {

    res.send('hello /');
}).get('/admin',function(req,res) {

    res.send('hello /admin');
}).post('/admin',function(req,res) {

    res.send('hello /admin');
}).get('/duplicate',function(req,res) {

    res.send('hello /duplicate');
}).get('/duplicate/:id',function(req,res) {

    res.send('hello /duplicate');
}).post('/foo',function(req,res) {

    res.send('hello /foo');
}).put('/nooo',function(req,res) {

    res.send('hello /nooo');
}).all('/all',function(req,res) {

    res.send('hello /all');
});

father.use(child);
console.log('starting "hello world" on port 3000');
sitemap = map();

console.log('Father');
console.log(sitemap.generate(father));
sitemap.reset();

console.log('Child');
console.log(sitemap.generate(child));
sitemap.reset();
```

**Comment by loganknecht** [comment]
No that is not what I am trying to do at all.

What I am trying to do is use the new Router object in Express 4 for my express object. And in turn, when I pass that express object to the express-sitemap object I want it to generate based on the routers added to the express object.

I have take the liberty of creating a public repository that is an example for this issue.
https://github.com/loganknecht/example_express_sitemap

If you pull that repository and type
```bash
npm start
```

The express app will run, AND it will output the Sitemap.xml and Robots.txt. However the sitemap.xml is an empty urlset element and does not populate the information that's configured for the router.

The full js file is here
```javascript
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'hbs');

// uncomment after placing your favicon in /public
//app.use(favicon(__dirname + '/public/favicon.ico'));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

//-----------------------------------------------------------------------------
// Custom Express Logic
//-----------------------------------------------------------------------------
var defaultRouter =  express.Router();
defaultRouter.get('/', function(request, response, next) {
    response.render('index', { title: 'Express' });
});
defaultRouter.get('/derp', function(request, response, next) {
    response.send('You done derped');
});
app.use('/', defaultRouter);
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Express-Sitemap Logic
//-----------------------------------------------------------------------------
var sitemap = require('express-sitemap');
sitemap = sitemap();
sitemap.generate4(app);
sitemap.toFile();
//-----------------------------------------------------------------------------

// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
        res.status(err.status || 500);
        res.render('error', {
            message: err.message,
            error: err
        });
    });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
        message: err.message,
        error: {}
    });
});


module.exports = app;
```
But the part that shows what I'm concerned about is this part
```javascript
//-----------------------------------------------------------------------------
// Custom Express Logic
//-----------------------------------------------------------------------------
var defaultRouter =  express.Router();
defaultRouter.get('/', function(request, response, next) {
    response.render('index', { title: 'Express' });
});
defaultRouter.get('/derp', function(request, response, next) {
    response.send('You done derped');
});
app.use('/', defaultRouter);
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Express-Sitemap Logic
//-----------------------------------------------------------------------------
var sitemap = require('express-sitemap');
sitemap = sitemap();
sitemap.generate4(app);
sitemap.toFile();
//-----------------------------------------------------------------------------
```

Does that make more sense?

**Comment by hex7c0** [comment]
thanks for your valuable feedback :+1: 
look at next commit

this is your example
```js
var map = require('..');
var express = require('express');
var father = express();
var child = express.Router();

child.get('/', function(req, res) {

  res.send('hello /');
}).get('/admin', function(req, res) {

  res.send('hello /admin');
}).post('/admin', function(req, res) {

  res.send('hello /admin');
}).get('/duplicate', function(req, res) {

  res.send('hello /duplicate');
}).get('/duplicate/:id', function(req, res) {

  res.send('hello /duplicate');
}).post('/foo', function(req, res) {

  res.send('hello /foo');
}).put('/nooo', function(req, res) {

  res.send('hello /nooo');
}).all('/all', function(req, res) {

  res.send('hello /all');
});

father.use(child);
father.listen(3000);
console.log('starting "hello world" on port 3000');
var sitemap = map();

console.log('Father');
console.log(sitemap.generate4(father));
sitemap.reset();

console.log('Child');
console.log(sitemap.generate4(child));
sitemap.reset();
```

**Comment by loganknecht** [comment]
Just wondering, do you intend to publish this change to the npm registry?

**Comment by hex7c0** [comment]
I'll bump a new version

**Comment by loganknecht** [comment]
Hey again.

I just used:
```bash
npm install
```
to install the new version of the express-sitemap module for the git repository example I had set up:
https://github.com/loganknecht/example_express_sitemap

However there does seem to be an issue with respect to my initial concern.

That is, when I perform the javascript functions like so I still get that empty xml configuration:
```javascript
//-----------------------------------------------------------------------------
// Custom Express Logic
//-----------------------------------------------------------------------------
var defaultRouter =  express.Router();
defaultRouter.get('/', function(request, response, next) {
    response.render('index', { title: 'Express' });
});
defaultRouter.get('/derp', function(request, response, next) {
    response.send('You done derped');
});
app.use('/', defaultRouter);
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Express-Sitemap Logic
//-----------------------------------------------------------------------------
var sitemap = require('express-sitemap');
sitemap = sitemap();
sitemap.generate4(app);
sitemap.toFile();
//-----------------------------------------------------------------------------
```
However when I use the configuration
```javascript
//-----------------------------------------------------------------------------
// Custom Express Logic
//-----------------------------------------------------------------------------
var defaultRouter =  express.Router();
defaultRouter.get('/', function(request, response, next) {
    response.render('index', { title: 'Express' });
});
defaultRouter.get('/derp', function(request, response, next) {
    response.send('You done derped');
});
app.use('/', defaultRouter);
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Express-Sitemap Logic
//-----------------------------------------------------------------------------
var sitemap = require('express-sitemap');
sitemap = sitemap();
sitemap.generate4(defaultRouter);
sitemap.toFile();
//-----------------------------------------------------------------------------
```
I get the xml file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>http://127.0.0.1/</loc>
    </url>
    <url>
        <loc>http://127.0.0.1/derp</loc>
    </url>
</urlset>
```

My initial concern with this issue is that when I assign the router object created using 
```javascript
var defaultRouter =  express.Router();
```
to my express object and I'm looking to generate the xml by passing in the express object (app), not by passing in the router that was added to the express object.

Is it unreasonable to ask that this be possible, because the ideal use case is that I create separate routers, add them to my express object via app.use, and then pass that express-object (app) into the sitemap.generate function. Then, when it outputs to the files, it outputs for all the routers attached to the express object.

**Comment by hex7c0** [comment]
Hi loganknecht,
I understand your request
but nested callback (like app.use(router)) aren't supported now

I'm working on it

**Comment by hex7c0** [comment]
https://github.com/hex7c0/express-sitemap/blob/master/examples/nested_router.js
